# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0001_squashed_0004_auto_20160501_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Marks a question as active/inactive. Inactive questions are notshown publicly and are only available to the question owner.', verbose_name='is active'),
        ),
    ]
