# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
        ('cs_activities', '0011_auto_20160421_1618'),
        ('cs_questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodingIoResponse',
        ),
        migrations.CreateModel(
            name='CodingIoResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Response')),
                ('source', models.TextField(blank=True)),
                ('feedback', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.response',),
        ),
    ]
