# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0006_auto_20160522_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingioresponse',
            name='question_for_unbound',
            field=models.ForeignKey(blank=True, help_text='Question object reference for unbound responses. This should be null for activity responses.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
        migrations.AlterField(
            model_name='numericresponse',
            name='question_for_unbound',
            field=models.ForeignKey(blank=True, help_text='Question object reference for unbound responses. This should be null for activity responses.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
    ]
