# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0007_auto_20160522_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionactivity',
            old_name='question',
            new_name='question_base',
        ),
    ]
