# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0011_auto_20160522_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='quiz',
        ),
    ]
