# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0015_auto_20160531_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='long_description',
            field=models.TextField(blank=True, help_text='A detailed explanation.', verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='no-description', help_text='A very brief one-phrase description used in listings.', max_length=140, verbose_name='short description'),
        ),
    ]
