# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='time_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='battle',
            name='time_end',
            field=models.DateTimeField(),
        ),
    ]
