# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_ranking', '0003_auto_20160405_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='cs_ranking.BattleResult'),
        ),
        migrations.AlterField(
            model_name='battleresult',
            name='battle_winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_ranking.Battle'),
        ),
    ]
