# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message_from_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(10, 'debug'), (20, 'info'), (25, 'success'), (30, 'warning'), (40, 'error')], default=20)),
                ('is_read', models.BooleanField(default=False, help_text='Was message read by the recipient?')),
                ('is_active', models.BooleanField(default=True, help_text='Is message active')),
                ('is_persistent', models.BooleanField(default=False, help_text='True if the the user needs to explicitly de-activate the message to make it inactive.')),
                ('payload', picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='Arbitrary object payload sent with the message', null=True)),
                ('message_from_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('message_to', models.ForeignKey(help_text='User instance recipient of the message', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cs_messages.message_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
