language: python

python:
  - "3.4"
  - "3.5"

# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install fake-factory
    - pip install lazy
    - pip install beautifulsoup4
    - pip install boxed
    - pip install bs4
    - pip install csscompressor
    - pip install decorator
    - pip install Django
    - pip install django-address
    - pip install django-annoying
    - pip install django-appconf
    - pip install django-autoslug
    - pip install django-bower
    - pip install django-compressor
    - pip install django-debug-toolbar
    - pip install django-extensions
    - pip install django-guardian
    - pip install django-jinja
    - pip install django-model-utils
    - pip install django-modelcluster
    - pip install django-picklefield
    - pip install django-taggit
    - pip install django-treebeard
    - pip install django-userena
    - pip install django-viewpack
    - pip install djangorestframework
    - pip install djinga
    - pip install easy-thumbnails
    - pip install frozendict
    - pip install generic
    - pip install html2text
    - pip install html5lib
    - pip install ipython
    - pip install ipython-genutils
    - pip install Jinja2
    - pip install jinja2-django-tags
    - pip install judge
    - pip install lazy
    - pip install Markdown
    - pip install MarkupSafe
    - pip install node
    - pip install numpy
    - pip install odict
    - pip install pandas
    - pip install pexpect
    - pip install pickleshare
    - pip install Pillow
    - pip install plumber
    - pip install ply
    - pip install psutil
    - pip install ptyprocess
    - pip install py
    - pip install pygeneric
    - pip install pytest
    - pip install python-dateutil
    - pip install pytuga
    - pip install pytz
    - pip install rcssmin
    - pip install rjsmin
    - pip install simplegeneric
    - pip install six
    - pip install slimit
    - pip install sqlparse
    - pip install traitlets
    - pip install Unidecode
    - pip install wagtail
    - pip install Willow
    - pip install zope.component
    - pip install zope.deprecation
    - pip install zope.event
    - pip install zope.interface
    - pip install zope.lifecycleevent
# command to run tests
script:
    - python src/manage.py test