# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20160330_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('battle_winner', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='ranking.BattleResult'),
        ),
    ]
