FORCE_JINJA_TEMPLATES = {
    # Userena templates
    'userena/activate_fail.html',
    'userena/password_reset_complete.html',
    'userena/activate_retry.html',
    'userena/password_reset_confirm_form.html',
    'userena/activate_retry_success.html',
    'userena/password_reset_done.html',
    'userena/base_userena.html',
    'userena/password_reset_form.html',
    'userena/disabled.html',
    'userena/profile_detail.html',
    'userena/email_change_complete.html',
    'userena/profile_form.html',
    'userena/email_confirm_complete.html',
    'userena/profile_list.html',
    'userena/email_confirm_fail.html',
    'userena/signin_form.html',
    'userena/email_form.html',
    'userena/signout.html',
    'userena/emails/',
    'userena/signup_complete.html',
    'userena/password_complete.html',
    'userena/signup_form.html',
    'userena/password_form.html',
}