# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0002_auto_20160501_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingioresponse',
            name='feedback',
        ),
    ]
