# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
        ('cs_questions', '0003_remove_codingioresponse_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingioactivity',
            name='answer_key',
        ),
        migrations.AddField(
            model_name='codingioactivity',
            name='language',
            field=models.ForeignKey(default='python', on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingioresponse',
            name='question_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_questions.CodingIoQuestion'),
        ),
    ]
