# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0003_auto_20160508_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
        migrations.AlterField(
            model_name='codingioresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
    ]
