# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0004_auto_20160508_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionactivity',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cs_questions.Question'),
        ),
    ]
