# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0005_auto_20160511_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingioresponse',
            old_name='question',
            new_name='question_for_unbound',
        ),
        
        migrations.RenameField(
            model_name='numericresponse',
            old_name='question',
            new_name='question_for_unbound',
        ),
    ]
