# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0008_auto_20160522_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionactivity',
            options={'verbose_name': 'question activity', 'verbose_name_plural': 'question activities'},
        ),
        migrations.AddField(
            model_name='questionactivity',
            name='recycle_unbound',
            field=models.BooleanField(default=False),
        ),
    ]
