# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0010_auto_20160522_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizactivity',
            options={'verbose_name': 'quiz activity', 'verbose_name_plural': 'quiz activities'},
        ),
        migrations.AlterField(
            model_name='quizactivityitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
    ]
