# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
        ('cs_questions', '0013_auto_20160523_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizactivity',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage'),
        ),
    ]
