# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeIoActivity',
            new_name='CodingIoActivity',
        ),
    ]
