# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0001_initial'),
        ('cs_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_courses.Discipline'),
        ),
    ]
