# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0003_auto_20160307_0239'),
        ('cs_questions', '0002_question_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeIoFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Feedback')),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.feedback',),
        ),
        migrations.CreateModel(
            name='QuestionActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='CodeIoActivity',
            fields=[
                ('questionactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_questions.QuestionActivity')),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.CodeIoAnswerKey')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_questions.questionactivity',),
        ),
        migrations.AddField(
            model_name='questionactivity',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question'),
        ),
    ]
