# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0002_auto_20160412_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingioquestion',
            name='iospec_size',
            field=models.PositiveIntegerField(default=0, help_text='The desired number of test cases that will be computedafter comparing the iospec template with the answer key.This is only a suggested value and will only be applied ifthe response template uses input commands to generaterandom input.', verbose_name='number of iospec template expansions'),
        ),
    ]
