# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0002_auto_20160619_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingioquestion',
            name='iospec_hash',
            field=models.CharField(blank=True, help_text='A hash to keep track of iospec updates.', max_length=32),
        ),
    ]
