# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0003_auto_20160307_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeiofeedback',
            name='answer_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codeiofeedback',
            name='case',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codeiofeedback',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codeiofeedback',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='codeiofeedback',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='codeiofeedback',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
