# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0004_auto_20160323_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeiofeedback',
            name='answer_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codeiofeedback',
            name='case',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codeiofeedback',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='codeiofeedback',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
