# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0005_auto_20160619_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingioquestion',
            name='grading_method',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='grading_method',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='grading_method',
        ),
    ]
