# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0006_auto_20160326_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeioquestion',
            old_name='response_template',
            new_name='iospec',
        ),
    ]
