# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:03
from __future__ import unicode_literals

import codeschool.models.mixins
import codeschool.models.wagtail
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('cs_questions', '0006_auto_20160619_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('page_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='quizlist_instance', serialize=False, to='wagtailcore.Page')),
                ('content_color', models.CharField(default='#10A2A4', help_text='Personalize the main color for page content.', max_length=20, verbose_name='color')),
            ],
            options={
                'abstract': False,
            },
            bases=(codeschool.models.wagtail.CodeschoolPageMixin, codeschool.models.mixins.MigrateMixin, 'wagtailcore.page'),
        ),
    ]
