# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0007_quizlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
