# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0008_auto_20160326_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeioanswerkey',
            old_name='prototype',
            new_name='question',
        ),
    ]
