# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0008_auto_20160619_2158'),
        ('cs_questions', '0008_delete_quizresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponseItem',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cs_core.responseitem',),
        ),
    ]
