# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0009_auto_20160326_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeiofeedback',
            name='title',
        ),
    ]
