# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_questions', '0009_quizresponseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='content_color',
        ),
        migrations.RemoveField(
            model_name='quizlist',
            name='content_color',
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='quizlist',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
    ]
