# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'length'), (1, 'time')], default=0)),
                ('battle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleResponse',
            fields=[
                ('codingioresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_questions.CodingIoResponse')),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='cs_battles.Battle')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_questions.codingioresponse',),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='cs_battles.BattleResponse'),
        ),
        migrations.AddField(
            model_name='battle',
            name='invitations_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_language', to='cs_core.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='battle',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_question', to='cs_questions.CodingIoQuestion'),
        ),
    ]
