# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('ref', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
