# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFormat',
            fields=[
                ('ref', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
