# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 02:52

from django.db import migrations


def system_objects(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'contenttype')
    
    # Profile root
    apps.get_model('cs_core', 'profileroot').objects.create(
        path="000100010001",
        depth=3,
        numchild=0,
        title="List of users",
        slug="users",
        url_path="/users/",
        locked=True,
        content_type=ContentType.objects.get_or_create(
            model='profileroot',
            app_label='cs_core',
        )[0],
    )
    
    # Hidden root
    apps.get_model('cs_core', 'hiddenroot').objects.create(
        path="00010002",
        depth=2,
        numchild=1,
        title="Hidden pages",
        slug="hidden",
        url_path="/hidden/",
        live=False,
        locked=True,
        content_type=ContentType.objects.get_or_create(
            model='hiddenroot',
            app_label='cs_core',
        )[0],
    )

    # Rogue root
    apps.get_model('cs_core', 'rogueroot').objects.create(
        path="000100020001",
        depth=3,
        numchild=0,
        title="Pages with no parent",
        slug="rogue",
        url_path="/rogue/",
        live=False,
        locked=True,
        content_type=ContentType.objects.get_or_create(
            model='rogueroot',
            app_label='cs_core',
        )[0],
    )

    # Fix the number of children in the root node
    root = apps.get_model('wagtailcore', 'page').objects.get(path='0001')
    root.numchild += 1
    root.save(update_fields=['numchild'])
    first_page = apps.get_model('wagtailcore', 'page').objects.get(path='00010001')
    first_page.numchild = 1
    first_page.save(update_fields=['numchild'])

    # File formats
    from cs_core.models.fileformat import format_processor

    def process(L):
        FileFormat = apps.get_model('cs_core', 'fileformat')
        for kwargs in L:
            FileFormat.objects.create(**kwargs)

    format_processor(process)


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
        ('wagtailcore', '0002_initial_data'),
    ]

    operations = [
        migrations.RunPython(system_objects),
    ]
