# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 15:06
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseitem',
            name='feedback_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='response_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
