# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0003_auto_20160619_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecontext',
            name='context_data',
        ),
        migrations.RemoveField(
            model_name='responsecontext',
            name='parent',
        ),
        migrations.AddField(
            model_name='responsecontext',
            name='data',
            field=wagtail.wagtailcore.fields.StreamField((), default=[]),
        ),
        migrations.AddField(
            model_name='responsecontext',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='responsecontext',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
