# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('cs_core', '0005_auto_20160619_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecontext',
            name='activity',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_core.ResponseContext'),
        ),
        migrations.AlterUniqueTogether(
            name='responsecontext',
            unique_together=set([('activity', 'name')]),
        ),
    ]
