# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0006_auto_20160619_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecontext',
            name='parent',
        ),
        migrations.AlterField(
            model_name='responsecontext',
            name='delayed_feedback',
            field=models.BooleanField(default=False, help_text='If set, students will be only be able to see the feedback after the activity expires its deadline.', verbose_name='delayed feedback'),
        ),
    ]
