# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0007_auto_20160619_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_core.ResponseContext'),
        ),
    ]
