# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 23:19
from __future__ import unicode_literals

import codeschool.models.wagtail
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('cs_core', '0008_auto_20160619_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootList',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=(codeschool.models.wagtail.CodeschoolPageMixin, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='responseitem',
            name='parent',
        ),
        migrations.AlterField(
            model_name='response',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Final grade given to activity considering all responses, penalties, etc.', max_digits=6, null=True, verbose_name='Final grade'),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='response',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cs_core.Response', verbose_name='response'),
        ),
    ]
