# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0009_auto_20160620_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseitem',
            name='response_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
