# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_questions', '0005_auto_20160511_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResponse',
            fields=[
                ('codingioresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_questions.CodingIoResponse')),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_questions.codingioresponse',),
        ),
        migrations.CreateModel(
            name='CodingIoBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('battle_winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_battles.BattleResponse')),
                ('invitations_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.CodingIoQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='battleresponse',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='cs_battles.CodingIoBattle'),
        ),
    ]
