# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_battles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingiobattle',
            name='invitations_user',
        ),
        migrations.AddField(
            model_name='codingiobattle',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
