# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import picklefield.fields


class Migration(migrations.Migration):

    replaces = [('cs_activities', '0001_initial'), ('cs_activities', '0002_auto_20160419_2205'), ('cs_activities', '0003_auto_20160419_2207'), ('cs_activities', '0004_auto_20160419_2231'), ('cs_activities', '0005_auto_20160420_2254'), ('cs_activities', '0006_synccodeactivity_synccodeedititem'), ('cs_activities', '0007_synccodeedititem_next'), ('cs_activities', '0008_auto_20160421_0928'), ('cs_activities', '0009_synccodeedititem_activity'), ('cs_activities', '0010_auto_20160421_1143'), ('cs_activities', '0011_auto_20160421_1618'), ('cs_activities', '0012_remove_response_data'), ('cs_activities', '0013_response_feedback_data'), ('cs_activities', '0014_auto_20160502_0001')]

    initial = True

    dependencies = [
        ('cs_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=140)),
                ('long_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cs_courses.Course')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'verbose_name': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('waiting', 'waiting'), ('done', 'done')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('grade', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Percentage of maximum grade')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback_data', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', help_text='Only open activities will be visible and active to all students.', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='date of publication', when=set(['open'])),
        ),
        migrations.AddField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cs_activities.Activity'),
        ),
        migrations.CreateModel(
            name='SyncCodeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='SyncCodeEditItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='cs_activities.SyncCodeEditItem')),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='cs_activities.SyncCodeActivity')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='activity',
            name='icon_src',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
