# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericactivity',
            old_name='description',
            new_name='long_description',
        ),
    ]
