# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group of students that can view this activity. Leave blank to assign to the whole classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group of students'),
        ),
        migrations.AlterField(
            model_name='response',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_activities.Activity'),
        ),
        migrations.AlterField(
            model_name='response',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
