# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:11
from __future__ import unicode_literals

import cs_activities.models.activity
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cs_activities', '0002_auto_20160504_1329'), ('cs_activities', '0003_auto_20160510_2229'), ('cs_activities', '0004_auto_20160510_2257'), ('cs_activities', '0005_auto_20160511_1023'), ('cs_activities', '0006_auto_20160511_1209'), ('cs_activities', '0007_auto_20160531_1916'), ('cs_activities', '0008_auto_20160531_1917'), ('cs_activities', '0009_auto_20160531_1924'), ('cs_activities', '0010_auto_20160531_1953'), ('cs_activities', '0011_auto_20160531_2054'), ('cs_activities', '0012_auto_20160531_2143'), ('cs_activities', '0013_auto_20160531_2150'), ('cs_activities', '0014_auto_20160531_2238'), ('cs_activities', '0015_auto_20160531_2327'), ('cs_activities', '0016_auto_20160531_2328'), ('cs_activities', '0017_auto_20160601_0908')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cs_activities', '0001_squashed_0014_auto_20160502_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synccodeedititem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='cs_activities.SyncCodeActivity'),
        ),
        migrations.AddField(
            model_name='response',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Similar to given_grade, but can account for additional factors such as delay penalties or any reason the teacher may want to override the student's grade.", max_digits=6, null=True, verbose_name='Final grade'),
        ),
        migrations.AddField(
            model_name='response',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='response',
            old_name='grade',
            new_name='given_grade',
        ),
        migrations.AlterField(
            model_name='response',
            name='given_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='This grade is given by the auto-grader and representsthe grade for the response before accounting for any bonuses or penalties.', max_digits=6, null=True, verbose_name='Percentage of maximum grade'),
        ),
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_multiple_responses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='responsegroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.Activity'),
        ),
        migrations.AddField(
            model_name='responsegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cs_activities.Response'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cs_activities.Activity'),
        ),
        migrations.AlterField(
            model_name='response',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cs_activities.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.TextField(default='no-description', verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(default='no-description', max_length=140, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.TextField(blank=True, help_text='A detailed explanation.', verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(default='no-description', help_text='A very brief one-phrase description used in listings.', max_length=140, verbose_name='short description'),
        ),
        migrations.CreateModel(
            name='FileDownloadActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('provide_compressed', models.BooleanField(default=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='')),
                ('targz_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.FileDownloadActivity')),
            ],
        ),
        migrations.CreateModel(
            name='PageActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='UrlActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.UrlActivity')),
                ('alt', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='urlitem',
            unique_together=set([('activity', 'index')]),
        ),
        migrations.AlterUniqueTogether(
            name='fileitem',
            unique_together=set([('activity', 'index')]),
        ),
        migrations.AlterModelOptions(
            name='filedownloadactivity',
            options={'verbose_name': 'file download list', 'verbose_name_plural': 'file download activities'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'response', 'verbose_name_plural': 'responses'},
        ),
        migrations.AlterModelOptions(
            name='urlactivity',
            options={'verbose_name': 'URL list', 'verbose_name_plural': 'url list activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allow_multiple_responses',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_as_owner', to='contenttypes.ContentType', verbose_name='owner model type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="owner model's id"),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_as_target', to='contenttypes.ContentType', verbose_name='target model type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="target model's id"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon_src',
            field=models.CharField(blank=True, help_text='Optional icon name that can be used to personalize the activity. Material icons are available by using the "material:" namespace as in "material:menu".', max_length=50),
        ),
        migrations.CreateModel(
            name='GradingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(blank=True, max_length=20)),
                ('data', models.TextField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Similar to given_grade, but can account for additional factors such as delay penalties or for any other reason the teacher may want to override the student's grade.", max_digits=6, null=True, verbose_name='Final grade'),
        ),
        migrations.AlterField(
            model_name='response',
            name='given_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='This grade is given by the auto-grader and represents the grade for the response before accounting for any bonuses or penalties.', max_digits=6, null=True, verbose_name='Percentage of maximum grade'),
        ),
        migrations.AlterUniqueTogether(
            name='responsegroup',
            unique_together=set([('user', 'activity')]),
        ),
        migrations.AddField(
            model_name='activity',
            name='grading_method',
            field=models.ForeignKey(blank=True, default=cs_activities.models.activity.grading_method_best, on_delete=django.db.models.deletion.CASCADE, to='cs_activities.GradingMethod'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingmethod',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.RenameModel(
            old_name='ResponseGroup',
            new_name='FinalResponse',
        ),
    ]
