# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:53
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0002_auto_20160412_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='ok', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
