# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:31
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0003_auto_20160419_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='date of publication', when=set(['open'])),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
