# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0003_auto_20160601_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
