# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0004_auto_20160419_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cs_activities.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', help_text='Only open activities will be visible and active to all students.', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
