# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0004_textualresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group of students that this activity is assigned to. Leave blank to assign to the whole classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group of students'),
        ),
        migrations.AlterField(
            model_name='response',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
