# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0002_sourceformat'),
        ('cs_activities', '0004_auto_20160604_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFileActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('provide_compressed', models.BooleanField(default=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='')),
                ('targz_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'file download activities',
                'verbose_name': 'file download list',
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('source', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.SourceFileActivity')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_core.SourceFormat')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sourceitem',
            unique_together=set([('activity', 'index')]),
        ),
    ]
