# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pbl', '0006_badge_image'),
        ('cs_activities', '0005_auto_20160606_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCodeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('provide_compressed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'file download activities',
                'verbose_name': 'file download list',
            },
            bases=('cs_activities.activity',),
        ),
        migrations.RemoveField(
            model_name='sourcefileactivity',
            name='activity_ptr',
        ),
        migrations.RenameField(
            model_name='sourceitem',
            old_name='language',
            new_name='format',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='name',
            field=models.CharField(default='python', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(upload_to='file-activities/'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.SourceCodeActivity'),
        ),
        migrations.DeleteModel(
            name='SourceFileActivity',
        ),
    ]
