# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0005_auto_20160315_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_grade',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
