# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:02
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0006_activity_max_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='open', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
