# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0006_auto_20160606_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecodeactivity',
            options={'verbose_name': 'source code fragment list', 'verbose_name_plural': 'source code fragment lists'},
        ),
        migrations.RemoveField(
            model_name='sourcecodeactivity',
            name='provide_compressed',
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='visible',
            field=models.BooleanField(default=True, help_text='Non-visible source items are available for download, but are not included in the main page', verbose_name='is visible'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the source code fragment. This field accepts Markdown.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='format',
            field=models.ForeignKey(default='txt', help_text='The file format for the source code.', on_delete=django.db.models.deletion.CASCADE, to='cs_core.SourceFormat', verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='name',
            field=models.CharField(help_text='A short description of the given source code fragment', max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='source',
            field=models.TextField(help_text='The source code fragment.', verbose_name='source'),
        ),
    ]
