# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0007_synccodeedititem_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
