# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0007_auto_20160606_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cs_courses.Course'),
        ),
    ]
