# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0008_auto_20160421_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccodeedititem',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='cs_activities.SyncCodeActivity'),
            preserve_default=False,
        ),
    ]
