# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0010_auto_20160421_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon_src',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='synccodeedititem',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='cs_activities.SyncCodeEditItem'),
        ),
    ]
