# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0011_auto_20160421_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='data',
        ),
    ]
