# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:36
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0012_remove_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='feedback_data',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
    ]
