# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 03:01
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0013_response_feedback_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='feedback_data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
