# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield1', models.PositiveIntegerField()),
                ('myfield2', models.TextField()),
            ],
        ),
    ]
