# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pbl', '0003_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='description',
            new_name='short_description',
        ),
    ]
