# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pbl', '0004_auto_20160518_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='users',
        ),
        migrations.AddField(
            model_name='badge',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='short_description',
            field=models.TextField(verbose_name='short description'),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
