# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pbl', '0005_auto_20160518_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='/static/badge/none.jpg', upload_to='static/badge'),
        ),
    ]
