# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields
import userena.models


class Migration(migrations.Migration):

    replaces = [('cs_auth', '0001_initial'), ('cs_auth', '0002_profile_school_id'), ('cs_auth', '0003_auto_20160510_2229')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUsername',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedUsernameListing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usernames', models.ManyToManyField(to='cs_auth.AllowedUsername')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable a custom field', verbose_name='enabled')),
                ('type', models.CharField(blank=True, choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], default='text', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.CustomFieldCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.CustomFieldDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('friend', 'friend'), ('acquaintance', 'acquaintance'), ('unfriend', 'unfriend')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_as_other', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'male'), (1, 'female')], null=True, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('website', models.URLField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('school_id', models.CharField(blank=True, help_text='Identification number in your school issued id card.', max_length=50, null=True, verbose_name='school id')),
            ],
            options={
                'permissions': (('student', "Can access/modify data visible to student's"), ('teacher', "Can access/modify data visible only to Teacher's")),
            },
        ),
        migrations.CreateModel(
            name='SingleUserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_group', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cs_auth.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together=set([('owner', 'other')]),
        ),
        migrations.AlterField(
            model_name='friendshipstatus',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users_as_other', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshipstatus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
