# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:42
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields
import userena.models


class Migration(migrations.Migration):

    replaces = [('cs_auth', '0001_initial'), ('cs_auth', '0002_auto_20160409_1146'), ('cs_auth', '0003_auto_20160409_1221'), ('cs_auth', '0004_auto_20160409_1503'), ('cs_auth', '0005_friendshipstatus'), ('cs_auth', '0006_auto_20160411_1205'), ('cs_auth', '0007_auto_20160411_1812'), ('cs_auth', '0008_auto_20160411_2142'), ('cs_auth', '0009_auto_20160411_2150'), ('cs_auth', '0010_customfielddefinition_enabled')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUsername',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedUsernameListing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usernames', models.ManyToManyField(to='cs_auth.AllowedUsername')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldCategory',
            fields=[
                ('ref', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], default='text', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.CustomFieldCategory')),
                ('required_permissions', models.ManyToManyField(to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.CustomFieldDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'male'), (1, 'female')], null=True, verbose_name='gender')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'permissions': (('view_profile', 'Can view profile'),),
            },
        ),
        migrations.CreateModel(
            name='SingleUserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_group', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('student', "Can access/modify data visible to student's"), ('teacher', "Can access/modify data visible only to Teacher's"))},
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cs_auth.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('friend', 'friend'), ('colleague', 'colleague'), ('unfriend', 'unfriend')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_as_other', to=settings.AUTH_USER_MODEL)),
                ('self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together=set([('self', 'other')]),
        ),
        migrations.RenameField(
            model_name='friendshipstatus',
            old_name='self',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together=set([('owner', 'other')]),
        ),
        migrations.RemoveField(
            model_name='customfieldcategory',
            name='ref',
        ),
        migrations.AddField(
            model_name='customfieldcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='required',
        ),
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='required_permissions',
        ),
        migrations.AlterField(
            model_name='customfieldcategory',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='customfieldcategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable a custom field', verbose_name='enabled'),
        ),
    ]
