# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
