# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_id',
            field=models.CharField(blank=True, help_text='Identification number in your school issued id card.', max_length=50, null=True, verbose_name='school id'),
        ),
    ]
