# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0001_squashed_0010_customfielddefinition_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
