# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_auth', '0002_auto_20160306_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUserGroup',
            fields=[
                ('usergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_auth.UserGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_auth.usergroup',),
        ),
    ]
