# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0003_singleusergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleUserGroup',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
