# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_auth', '0004_auto_20160409_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('friend', 'friend'), ('colleague', 'colleague'), ('unfriend', 'unfriend')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_as_other', to=settings.AUTH_USER_MODEL)),
                ('self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
