# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0005_friendshipstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together=set([('self', 'other')]),
        ),
    ]
