# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0006_auto_20160411_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshipstatus',
            old_name='self',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cs_auth.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together=set([('owner', 'other')]),
        ),
    ]
