# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0007_auto_20160411_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldcategory',
            name='ref',
        ),
        migrations.AddField(
            model_name='customfieldcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
