# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0008_auto_20160411_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='required',
        ),
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='required_permissions',
        ),
        migrations.AlterField(
            model_name='customfieldcategory',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='customfieldcategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
