# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:41
from __future__ import unicode_literals

import cs_pages.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', cs_pages.models.LanguageChooserBlock()), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('interactive_code', wagtail.wagtailcore.blocks.StructBlock((('language', cs_pages.models.LanguageChooserBlock()), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))),
        ),
    ]
