# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0001_squashed_0003_course_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='courses_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
