# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='current_lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='current_lesson_index',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='current_lesson_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
