# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
        migrations.AddField(
            model_name='faculty',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='short_description',
            field=models.TextField(default='no-description', verbose_name='short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
    ]
