# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_courses', '0002_auto_20160409_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='course_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
