# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0002_auto_20160531_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='short_description',
            field=models.TextField(default='no-description', verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_description',
            field=models.TextField(default='no-description', verbose_name='short description'),
        ),
    ]
