# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_courses', '0002_auto_20160307_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_expired',
        ),
    ]
