# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='simplevote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_polls.Option'),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_votes', to='cs_polls.Poll'),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternativevote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_votes', to='cs_polls.Poll'),
        ),
        migrations.AddField(
            model_name='alternativevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
