# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_polls', '0003_auto_20160518_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='forbidden_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cs_polls.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
    ]
