# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_polls', '0005_auto_20160518_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='forbidden_users',
            new_name='voters',
        ),
    ]
