# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0003_auto_20160510_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='grade',
            new_name='given_grade',
        ),
    ]
