# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_activities', '0004_auto_20160510_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_multiple_responses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='responsegroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_activities.Activity'),
        ),
        migrations.AddField(
            model_name='responsegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
