# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0005_auto_20160511_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cs_activities.Response'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cs_activities.Activity'),
        ),
        migrations.AlterField(
            model_name='response',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cs_activities.Activity'),
        ),
    ]
