# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0007_auto_20160531_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_description',
            field=models.CharField(default='no-description', max_length=140, verbose_name='short description'),
        ),
    ]
