# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:38
from __future__ import unicode_literals

import cs_activities.models.activity
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0013_auto_20160531_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='grading_method_object',
            field=models.ForeignKey(blank=True, default=cs_activities.models.activity.grading_method_best, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_activities.GradingMethod'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="owner model's id"),
        ),
    ]
