# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:28
from __future__ import unicode_literals

import cs_activities.models.activity
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0015_auto_20160531_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grading_method',
            field=models.ForeignKey(blank=True, default=cs_activities.models.activity.grading_method_best, on_delete=django.db.models.deletion.CASCADE, to='cs_activities.GradingMethod'),
        ),
    ]
