# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_activities', '0002_auto_20160504_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Similar to given_grade, but can account for additional factors such as delay penalties or any reason the teacher may want to override the student's grade.", max_digits=6, null=True, verbose_name='Final grade'),
        ),
        migrations.AddField(
            model_name='response',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='This grade is given by the auto-grader and representsthe grade for the response before accounting for any bonuses or penalties.', max_digits=6, null=True, verbose_name='Percentage of maximum grade'),
        ),
    ]
