# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cs_activities', '0010_auto_20160531_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedownloadactivity',
            options={'verbose_name': 'file download list', 'verbose_name_plural': 'file download activities'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'response', 'verbose_name_plural': 'responses'},
        ),
        migrations.AlterModelOptions(
            name='urlactivity',
            options={'verbose_name': 'URL list', 'verbose_name_plural': 'url list activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allow_multiple_responses',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_as_owner', to='contenttypes.ContentType', verbose_name='owner model type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="onwer model's id"),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_as_target', to='contenttypes.ContentType', verbose_name='target model type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="target model's id"),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='icon_src',
            field=models.CharField(blank=True, help_text='Optional icon name that can be used to personalize the activity. Material icons are available by using the "material:" namespace as in "material:menu".', max_length=50),
        ),
    ]
